name: diag_text
on:
  workflow_dispatch:
  push:
    branches: [ diag_text ]
jobs:
  d:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: dump c2d text.h + font.h
        run: |
          echo "===== c2d/text.h ====="
          cat /opt/devkitpro/libctru/include/c2d/text.h
          echo "===== c2d/font.h ====="
          cat /opt/devkitpro/libctru/include/c2d/font.h
